# Generated by Django 5.1.2 on 2024-11-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohouseAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='is_loisted_by_agent',
            new_name='is_listed_by_agent',
        ),
    ]
