# Generated by Django 5.1.2 on 2024-11-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cohouseAPI', '0002_rename_is_loisted_by_agent_property_is_listed_by_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to, A user will get all permissions granted to each of their groups', related_name='cohouseAPI_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user. A user will get all permissions granted to each of their groups.', related_name='cohouseAPI_user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
