# Generated by Django 5.1.2 on 2024-11-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohouseAPI', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord'), ('agent', 'Agent')], max_length=10),
        ),
    ]
